### ISSUE TITLE
error":{"code":-32003

### ISSUE THREAD

**Issue by AcoustiCoder** [bmresearch/Solnet.Metaplex#12]
Transaction sim:
 {"jsonrpc":"2.0","error":{"code":-32003,"message":"Transaction signature verification failure"},"id":1}

I cant mint nft.

This is my code: 

`  

           var rpcClient = ClientFactory.GetClient(Cluster.MainNet); 
            var blockHash = rpcClient.GetRecentBlockHash();
            var wallet = new Wallet(MnemonicWords);

            var fromAccount = wallet.Account;
            var mintAccount = wallet.GetAccount(0);
            var tokenAccount = wallet.GetAccount(0);

            byte[] metadataAddress = new byte[32];
            int nonce;
            AddressExtensions.TryFindProgramAddress(
                new List<byte[]>() {
                    Encoding.UTF8.GetBytes("metadata"),
                    MetadataProgram.ProgramIdKey,
                    mintAccount.PublicKey
                },
                MetadataProgram.ProgramIdKey,
                out metadataAddress,
                out nonce
            );

            Console.WriteLine($"PDA METADATA: {new PublicKey(metadataAddress)}");
            byte[] masterEditionAddress = new byte[32];
            //int nonce;
            AddressExtensions.TryFindProgramAddress(
                new List<byte[]>() {
                    Encoding.UTF8.GetBytes("metadata"),
                    MetadataProgram.ProgramIdKey,
                    mintAccount.PublicKey
                },
                MetadataProgram.ProgramIdKey,
                out masterEditionAddress,
                out nonce
            );
            Console.WriteLine($"PDA MASTER: {new PublicKey(masterEditionAddress)}");

          
            var c1 = new Creator(fromAccount.PublicKey, 100);
         
      
            var data = new MetadataParameters()
            {
                name = "Test 2",
                symbol = "",
                image = "https://i.resmim.net/hddxqQ.jpg",
                uri = "http://foodi.com",
                creators = new List<Creator>() { c1 },
                sellerFeeBasisPoints = 5
            };

            byte[] TX2 = new TransactionBuilder()
                .SetRecentBlockHash(blockHash.Result.Value.Blockhash)
                .SetFeePayer(fromAccount)
                .AddInstruction(
                    MetadataProgram.CreateMetadataAccount(
                        new PublicKey(metadataAddress), //PDA
                        mintAccount.PublicKey,  //MINT
                        fromAccount.PublicKey,  //mint AUTHORITY
                        fromAccount.PublicKey,  //PAYER
                        fromAccount.PublicKey,
                        data,                   //DATA
                        true,
                        false                    //ISMUTABLE
                    )
                )
                .AddInstruction(
                    MetadataProgram.PuffMetada(
                        new PublicKey(metadataAddress)
                    )
                )
                .AddInstruction(
                    MetadataProgram.CreateMasterEdition(
                        1,
                        new PublicKey(masterEditionAddress),
                        mintAccount.PublicKey,
                        fromAccount.PublicKey,
                        fromAccount.PublicKey,
                        fromAccount.PublicKey,
                        new PublicKey(metadataAddress)
                    )
                )
                .Build(new List<Account> { fromAccount, wallet.GetAccount(0) });
            var txSim2 = rpcClient.SendTransaction(TX2);
            Console.WriteLine($"Transaction sim: \n { txSim2.RawRpcResponse }");`

**Comment by murlokito** [comment]
```
var fromAccount = wallet.Account;
var mintAccount = wallet.GetAccount(0);
var tokenAccount = wallet.GetAccount(0);
```

```
            .Build(new List<Account> { fromAccount, wallet.GetAccount(0) });
```

You are signing the transaction with the same key twice.

**Comment by AcoustiCoder** [comment]
> ```
> var fromAccount = wallet.Account;
> var mintAccount = wallet.GetAccount(0);
> var tokenAccount = wallet.GetAccount(0);
> ```
> 
> ```
>             .Build(new List<Account> { fromAccount, wallet.GetAccount(0) });
> ```
> 
> You are signing the transaction with the same key twice.

i removed one of them. And now im getting another error. I think there is progress..
If you can help me, i will be appreciate.


` {"jsonrpc":"2.0","error":{"code":-32002,"message":"Transaction simulation failed: Error processing Instruction 0: Program failed to complete","data":{"accounts":null,"err":{"InstructionError":[0,"ProgramFailedToComplete"]},"logs":["Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]","Program log: Instruction: Create Metadata Accounts","Program log: libstd rust_begin_panic","Program log: panicked at 'range end index 36 out of range for slice of length 0', token-metadata/program/src/utils.rs:234:27","Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 200000 of 200000 compute units","Program failed to complete: BPF program panicked","Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete"]}},"id":1}`

**Comment by mariomatic** [comment]
If you look a the MetadaTest.cs code you will see that the mint and token account are created in a prior transaction. Seeing you are using the same account as a fromAccount and mintAccount, I have to ask did you create a mint first?

**Comment by AcoustiCoder** [comment]
No, i actually dont know how nft system is work. im really trying to understand. do you have example code? it can help me to understand.

> If you look a the MetadataTest.cs code you will see that the mint and token account are created in a prior transaction. Seeing you are using the same account as a fromAccount and mintAccount, I have to ask did you create a mint first?

**Comment by mariomatic** [comment]
NFTs on Solana work as SPL tokens with 0 decimals and distribution of only 1 token. After that , you create a metadata account that holds the metadata and then master edition which controls the "printing of NFTs" ( maybe you want more then edition as a poster print ie). So its : create a mint-> mint 1 token -> create metadata account -> create masterEdition account. All that gives you a NFT.
In the Solnet.Metaplex.Test/Metadata.cs you will find two test functions: MintToken and TestCreateMetadataAccount. They are both needed to make a NFT. It simply doesn't fit in 200000 compute operations constraint of a transaction.

You can find out more at http://docs.metaplex.com and Metaplexes discord.

**Comment by AcoustiCoder** [comment]
I understand everything and now i can create nft with no problem. First, thank you both @murlokito and @mariomatic.

Now i have a new question. I really understand everything but i dont understand how i create nft with image? 

Im trying send bytes with my image and it doesnt work.

`

internal static byte[] EncodeCreateMetadataAccountData( MetadataParameters parameters,  bool isMutable = true  )
 {
            byte[] encodedName = Serialization.EncodeRustString(parameters.name);
            byte[] encodedSymbol = Serialization.EncodeRustString(parameters.symbol);
            byte[] encodedUri = Serialization.EncodeRustString(parameters.uri);


            var buffer = new MemoryStream();
            BinaryWriter writer = new BinaryWriter(buffer);

            //  I download my image to byte array
            var webClient = new WebClient();
            byte[] imageBytes = webClient.DownloadData(parameters.image);

             //  encodedImage is Encode Rust image
            byte[] encodedImage = new byte[imageBytes.Length + sizeof(uint)];
            encodedImage.WriteU32((uint)imageBytes.Length, 0);
            encodedImage.WriteSpan(imageBytes, sizeof(uint));
           
            writer.Write((byte)MetadataProgramInstructions.Values.CreateMetadataAccount);
            writer.Write(encodedName);
            writer.Write(encodedSymbol);

            writer.Write(encodedUri);
            writer.Write((ushort)parameters.sellerFeeBasisPoints);

            if (parameters.creators == null || parameters.creators?.Count < 1)
            {
                writer.Write(new byte[] { 0 }); //Option()
            }
            else
            {
                writer.Write((byte)1);
                writer.Write(parameters.creators.Count);
                foreach (Creator c in parameters.creators)
                {
                    byte[] encodedCreator = c.Encode();
                    writer.Write(encodedCreator);
                }
            }
           
           //here i write my encoded image.
            writer.Write(encodedImage);
            writer.Write(isMutable);
            return buffer.ToArray();
        }`

**Comment by mariomatic** [comment]
You upload your file somewhere ( Metaplex uploads it to Arweave ). Then you  put that uri link inside of a json, and then upload a json somewhere, and then put the link to the json inside of data uri field. Yes , it's complicated...

So, no we don't put the media data inside of the metadata ( that would be an atomic nft, I think only Arweave has them ).

You can read about the nft json standard:
https://docs.metaplex.com/nft-standard

**Comment by AcoustiCoder** [comment]
Solnet library has a code for upload json? How can i integrate json with solnet.metaplex? if you have an example code for it, i will be appreciated
