### ISSUE TITLE
[Bug] SystemProgram.SysVarRentKey

### ISSUE THREAD

**Issue by Intekai** [bmresearch/Solnet.Metaplex#26]
if i update library i have this error:

AccountMeta.ReadOnly(SystemProgram.SysVarRentKey, false)

**SystemProgram.SysVarRentKey**  not found

**Comment by mariomatic** [comment]
I can't recreate the  bug. Can you give me more context?

**Comment by Intekai** [comment]
If you update the library see the problem

**Comment by mariomatic** [comment]
Fixed by #27
