### ISSUE TITLE
[Bug] Could not load type 'Solnet.Rpc.Utilities.AddressExtensions' from assembly 'Solnet.Rpc

### ISSUE THREAD

**Issue by ohaddahan** [bmresearch/Solnet.Metaplex#39]
**Describe the bug**
Getting the following excepton:
```
Unhandled exception. System.TypeLoadException: Could not load type 'Solnet.Rpc.Utilities.AddressExtensions' from assembly 'Solnet.Rpc, Version=6.0.6.0, Culture=neutral, PublicKeyToken=null'.
   at Solana.Metaplex.MetadataAccount.GetAccount(IRpcClient client, PublicKey pk)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Solana.Metaplex.MetadataAccount.GetAccount(IRpcClient client, PublicKey pk)
```

**To Reproduce**
```
    var rpcClient = ClientFactory.GetClient(Cluster.DevNet, null);
    var tokenAccounts = rpcClient.GetTokenAccountsByOwner("A4dqTiSyoQPYaYKgz7KMC4KbsA7Hw4o1W9edXa949zzT", null,
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");

    Task.Run(async () =>
    {
        foreach (TokenAccount accountPk in tokenAccounts.Result.Value)
        {
            var mint = accountPk.Account.Data.Parsed.Info.Mint;
            var account = await MetadataAccount.GetAccount(rpcClient, new PublicKey(mint));
        }
    }).GetAwaiter().GetResult();
```
Installed versions:

![image](https://user-images.githubusercontent.com/20769037/159486151-21edd1c8-23d7-428b-9f09-521264f743a5.png)

**Expected behavior**
Not to crash.

**Desktop (please complete the following information):**
Macbook Pro latest OS.

**Comment by ohaddahan** [comment]
FYI examples show as `Solnet.Metaplex` and `NuGet` is `Solana.Metaplex`.

**Comment by ohaddahan** [comment]
Never mind, had to install it manually, that `Solana.Metaplex` package is confusing.

**Comment by aibalamar** [comment]
I have the same problem with the same versions of nuget but I can't solve it by installing it manually, maybe I'm doing it wrong, but I can't find the Solnet.Rpc.Utilities.AddressExtensions class documented [here](https://blockmountain.io/Solnet/api/Solnet.Rpc.Utilities.AddressExtensions.html)

![imagen](https://user-images.githubusercontent.com/102263603/159806071-8f47ffef-931a-4a17-b366-23d0a9d75913.png)

**Comment by BifrostTitan** [comment]
Updated the nuget package with the latest source. Try again after updating the package
