### ISSUE TITLE
Encode payload data for CreateMetadataAccountV3 (with Collections Details)

### ISSUE THREAD

**Issue by mihneacalugaru** [bmresearch/Solnet.Metaplex#42]
I am aware that there has not yet been released a version which takes into account certified collections. Anyway, I do plan to make the necessary adjustments to the existing code so as to allow creating a collection.

From my understanding, for creating a certified collection, the following are needed:

- Changing `MetadataProgram.CreateMetadataAccount` function so as to also encode the `collectionDetails`. However, I tried to change it according to the order, offsets and sizes of arguments listed here https://docs.metaplex.com/programs/token-metadata/instructions#create-a-metadata-account and I don't seem to manage to get it working. My modified version of `MetadataProgram.CreateMetadataAccount` is:
```cs
private static byte[] EncodeCreateMetadataAccountData(MetadataParameters parameters, int? collectionDetailsSize = null, bool isMutable = true)
        {
            byte[] bytes = Encoding.UTF8.GetBytes(parameters.name);
            byte[] bytes2 = Encoding.UTF8.GetBytes(parameters.symbol);
            byte[] bytes3 = Encoding.UTF8.GetBytes(parameters.uri);
            MemoryStream memoryStream = new MemoryStream();
            BinaryWriter binaryWriter = new BinaryWriter(memoryStream);
            binaryWriter.Write((byte)0);
            binaryWriter.Write(bytes.Length);
            binaryWriter.Write(bytes);
            binaryWriter.Write(bytes2.Length);
            binaryWriter.Write(bytes2);
            binaryWriter.Write(bytes3.Length);
            binaryWriter.Write(bytes3);
            binaryWriter.Write((ushort)parameters.sellerFeeBasisPoints);
            int num;
            if (parameters.creators != null)
            {
                List<Creator> creators = parameters.creators;
                num = ((creators != null && creators.Count < 1) ? 1 : 0);
            }
            else
            {
                num = 1;
            }

            if (num != 0)
            {
                binaryWriter.Write((byte)0);
            }
            else
            {
                binaryWriter.Write((byte)1);
                binaryWriter.Write(parameters.creators.Count);
                foreach (Creator creator in parameters.creators)
                {
                    byte[] buffer = creator.Encode();
                    binaryWriter.Write(buffer);
                }
            }

            // collection - ADDED BY ME
            binaryWriter.Write((byte)0);

            // uses  - ADDED BY ME
            binaryWriter.Write((byte)0);

            binaryWriter.Write(isMutable);

            // - whole below if-else block ADDED BY ME
            if (collectionDetailsSize != null)
            {
                binaryWriter.Write((byte)1);

                byte[] collectionDetailsByteArray = new byte[8];
                var collectionDetailsSizeBytes = BitConverter.GetBytes(collectionDetailsSize.Value);

                collectionDetailsSizeBytes.CopyTo(collectionDetailsByteArray, 0);

                binaryWriter.Write(collectionDetailsByteArray);
            }
            else
            {
                binaryWriter.Write((byte)0);
            }

            return memoryStream.ToArray();
        }
```

I always get a deserialization exception from the on-chain program. I am using testnet at the moment. Can you help me get the encoding of the `collectionDetails` right until the feature will be implemented in this repo? Also, as I am in the need of using this quite often, I will be delighted to also contribute to the project.

Thank you very much!

**Comment by BifrostTitan** [comment]
Ive implemented MetadataAccount V3 instructions just waiting on the merge from @mariomatic . 
Feel free to use my fork that has it implemented.  https://github.com/BifrostTitan/Solnet.Metaplex  

This is what you were looking for. It took me several hours to figure this out. 

            if(collectionDetails == 0)
            {
                writer.Write((byte)0);  // 0 = null | No collection details
            }
            else
            {
                writer.Write((byte)1);
                writer.Write((byte)0); // collection detail size sits in an array - this byte defines its position | should always be 0
                writer.Write((ulong)collectionDetails); //collection details size of V1 defined as a ulong
                
            }
